bookseller/apps/register/urls.py
from django.conf.urls import patterns, url
from bookseller.apps.register import views

urlpatterns = patterns('',
    url(r'^(\d+)/$', views.account),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^register/$', views.register, name='register'),
    url(r'^errors/invalid_login/$', views.error_login_invalid),
    url(r'^messages/$', views.messages)
)

bookseller/urls.py
from django.conf.urls import patterns, include, url
from bookseller import settings
# Uncomment the next two lines to enable the admin:
from bookseller.apps.main import views
from django.contrib import admin
admin.autodiscover()
from django.conf.urls.static import static

handle404 = 'bookseller.apps.main.http_errors_views.show_404_view'
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'bookseller.views.home', name='home'),
    # url(r'^bookseller/', include('bookseller.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),

    url(r'^$', views.show_index),
    url(r'^search/$', views.search),
    url(r'^item/', include('bookseller.apps.main.urls')),
    url(r'^account/', include('bookseller.apps.register.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^list/(.*)/(\d+)/$', 'bookseller.apps.register.views.list'),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT})

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookseller/apps/register/forms.py
# coding:utf-8
from __future__ import unicode_literals
from django import forms

class RegisterForm(forms.Form):
    """
    Register Form, parse in register.html
    """
    username = forms.CharField(label='username', max_length=30)
    e_mail = forms.CharField(label='e_mail', max_length=75)
    password = forms.CharField(label='password', max_length=16,)
    phone_number = forms.CharField(label='phone_number', max_length=11)
    qq_number = forms.CharField(label='qq_number', max_length=15)
    address = forms.CharField(label='address', max_length=256)
    #errors = {'username': '用户名不正确', 'e_mail': 'e_mail地址不正确', 'password': '密码格式不正确'}



class LoginForm(forms.Form):
    """
    Login Form, parse in login.html
    """
    username = forms.CharField(label='username', max_length=30)
    password = forms.CharField(label='password', max_length=16,
                               widget=forms.PasswordInput)

    #errors = {'username': '用户名不正确', 'password': '密码格式不正确'}

class MessageForm(forms.Form):
    from_id = forms.CharField(label='from_id', max_length=30)
    to_id = forms.CharField(label='to_id', max_length=30)
    item_id = forms.CharField(label='item_id', max_length=30)
    content = forms.CharField(max_length=256)

bookseller/apps/register/views.py
# coding:utf-8
from __future__ import unicode_literals
import time
from django.http import HttpResponse
from django.http import HttpRequest

from django.http import HttpResponseRedirect
from django.db.models import Q
from django.template import Context
from django.template.loader import get_template

from django import forms
from django.contrib import auth
from django.contrib.auth.models import User
from django.shortcuts import render_to_response, RequestContext
from django.http import Http404

from forms import RegisterForm, LoginForm
from bookseller.apps.main.models import UserInfo, Item, Tags, Messages
from django.contrib.auth.decorators import login_required

@login_required(login_url='/account/login/')
def list(request, tag_name, page_num):
    if tag_name != '全部':
        try:
            tag = Tags.objects.get(name=tag_name)
        except Tags.DoesNotExist:
            raise Http404

        item_list = Item.objects.filter(tag=tag).order_by('-published_time')
        items_count_num = Item.objects.filter(tag=tag).order_by('-published_time').count()
    else:
        item_list = Item.objects.order_by('-published_time')
        items_count_num = Item.objects.order_by('-published_time').count()

    page_num = int(page_num)
    list_length = 2
    posts = {}
    item_list = item_list[list_length * (page_num - 1):list_length * page_num]
    posts['page_number'] = page_num
    posts['pages_count_number'] = -(-items_count_num / list_length)
    posts['previous_page_number'] = page_num - 1
    posts['next_page_number'] = page_num + 1
    if page_num > posts['pages_count_number']:
        raise Http404
    if page_num > 1:
        posts['has_previous'] = True
    if page_num < posts['pages_count_number']:
        posts['has_next'] = True
    tag_list = Tags.objects.all().order_by('id')

    return render_to_response('list.html', {'item_list': item_list, 'posts': posts, 'tag_list': tag_list},
                              context_instance=RequestContext(request))


def show_search(request):
    return render_to_response('search.html', context_instance=RequestContext(request))


def register(request):
    """
    This function is used to process registration requests
    """
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            print "form is valid"
            info_dict = form.cleaned_data
            new_user = User.objects.create_user(username=info_dict['username'],
                                                email=info_dict['e_mail'],
                                                password=info_dict['password'])
            new_user.is_active = True
            #new_user.date_joined = time.asctime()
            new_user.save()
            new_user_info = UserInfo(user_id=new_user,
                                     phone_number=int(info_dict['phone_number']),
                                     qq_number=int(info_dict['qq_number']),
                                     address=info_dict['address'])
            new_user_info.save()
            user = auth.authenticate(username=info_dict['username'], password=info_dict['password'])
            auth.login(request, user)
            return HttpResponseRedirect('/')
        else:
            print "form is not valid"
            return HttpResponseRedirect('/account/register/')
    else:
        form = RegisterForm()
    return render_to_response('register.html', {'school_list': ['西安电子科技大学']}, context_instance=RequestContext(request))


#def my_login(request):
#    if request.method == 'POST':
#        return login(request=request, template_name='login.html', )
#
#def my_logout(request):
#    return logout(request=request, template_name='logout.html')

def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            # 使用  username 和 password 的认证登录系统
            user = auth.authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password'])
            #print user

            # 注册完成后直接登录
            if user != None:
                auth.login(request, user)
                return HttpResponseRedirect('/')
            else:
                return HttpResponseRedirect('/account/errors/invalid_login/')
        else:
            return HttpResponseRedirect("/account/errors/invalid_login/")
    else:
        form = LoginForm()
    return render_to_response('login.html', {'form': form}, context_instance=RequestContext(request))


def logout(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect('/')
    else:
        auth.logout(request)
        return HttpResponseRedirect('/')


@login_required(login_url='/account/login/')
def account(request, id):
    user_id = int(id)
    #if user_id == User.objects.get(username=user.username).id:
    #    return render_to_response('account.html', {})
    #else:
    try:
        account_user = User.objects.get(id=user_id)
    except User.DoesNotExist:
        raise Http404
    account_user_info = UserInfo.objects.get(user_id=user_id)
    render_dict = {}
    render_dict['name'] = account_user.username
    render_dict['email'] = account_user.email
    render_dict['phone_number'] = account_user_info.phone_number
    render_dict['qq_number'] = account_user_info.qq_number
    render_dict['address'] = account_user_info.address
    #print render_dict
    item_list = Item.objects.filter(owner=account_user).order_by('-published_time')

    return render_to_response('person.html', {'user_info': render_dict, 'item_list': item_list},
                              context_instance=RequestContext(request))


@login_required(login_url='/account/login/')
def messages(request):
    user = User.objects.get(username=request.user.username)

    # about django.db.models.Q(), to see:
    # https://docs.djangoproject.com/en/1.5/topics/db/queries/
    # If you need to execute more complex queries (for example, queries with OR statements), you can use Q objects.
    # 选择 form_id 或者 to_id 是 当前用户的 Messages
    message_list = Messages.objects.filter(Q(from_id=user) | Q(to_id=user))

    print message_list
    return render_to_response('messages.html', {'message_list': message_list}, context_instance=RequestContext(request))


def error_login_invalid(request):
    return render_to_response('errors/invalid_login.html', {}, context_instance=RequestContext(request))

bookseller/apps/register/templates/index.html
{% extends "base.html" %}

{% block title %}十号地摊{% endblock %}

{% block content %}
<link href='http://www.youziku.com/webfont/CSS/9e103767539a663f5c89be56bc4e813f' rel='stylesheet' type='text/css'/>
<style>
    body{
        background-image :url(../../../static/image/index.jpg);
        background-size: cover;
        background-attachment: fixed;
        color:#428bca ;
    }
    .col-md-4{
        width: 27.333%;
        margin-right: 3%;
        margin-left: 3%;
    }
    .well{
        margin-top: 4%;
        opacity: 0.6;
        height: 400px;
        text-align: center;
        transition:opacity 1.5s;
        -moz-transition:opacity 1.5s, -moz-transform 2s; /* Firefox 4 */
        -webkit-transition:opacity 1.5s, -webkit-transform 2s; /* Safari and Chrome */
        -o-transition:opacity 1.5s,  -o-transform 2s; /* Opera */
    }
    img{
        margin-top: 40px;
        height: 30%;
    }
    .title{
        margin-top: 120px;
        margin-bottom: 150px;
        color: #ffffff;
        text-align: center;
    }
    .title2{
        padding-top: 300px;
        margin-bottom: 300px;
        color: #ffffff;
        text-align: center;
    }
    h1.header{
        font-size: 6em;
    }
    .well:hover{
        opacity:1;
    }
    #sellerQuickstart{
        margin-bottom: 100px;
    }
    footer{
        opacity: 0;
    }

</style>
<div class="container">
    <div id="title" class="row title">
        <h1 class="header" style="font-family:zhimang-xing41909;font-size: 9em ">十号地摊</h1>
        <h2>让闲置重新焕发光彩</h2>
        <a class="btn btn-lg btn-info" href="#buy">我要买东西</a>
        <a class="btn btn-lg btn-warning" href="#sell">我要卖东西</a>
    </div>
    <div id="buy" class="row title2" >
        <h1 class="header">我想要买二手</h1>
    </div>
    <div id="buyQuickstart" class="row">
        <a href="./list/全部/1/">
        <div class="col-md-4 well">

            <h2>第一步</h2>
            <h3>寻找你想要的东西</h3>
            <img src="../../../static/image/first.png" />
        </div>
        </a>
        <a href="./account/messages">
        <div class="col-md-4 well">

            <h2>第二步</h2>
            <h3>联系拥有者</h3>
            <img src="../../../static/image/second.png" />
        </div>
        </a>
        <div class="col-md-4 well">
            <h2>第三步</h2>
            <h3>约好时间，线下交易</h3>
            <img src="../../../static/image/third.png" />
        </div>
    </div>
        <div id="sell" class="row title2">
        <h1 class="header">我想要卖二手</h1>
    </div>
    <div id="sellerQuickstart" class="row">
        <a href="./item/create/">
        <div class="col-md-4 well">

            <h2>第一步</h2>
            <h3>发布你要卖的东西</h3>
            <img src="../../../static/image/first.png" />
        </div>
        </a>
        <a href="./account/messages">
        <div class="col-md-4 well">

            <h2>第二步</h2>
            <h3>等待买家联系</h3>
            <img src="../../../static/image/second.png" />
        </div>
        </a>
        <div class="col-md-4 well">
            <h2>第三步</h2>
            <h3>约好时间，线下交易</h3>
            <img src="../../../static/image/third.png" />
        </div>
    </div>
    <div id="login">
        <!--{% if not user.is_authenticated %}-->
        <!--<form class="form-horizontal col-md-6 well" role="form">-->
            <!--<div class="form-group">-->
                <!--<label for="id_username" class="col-sm-2 control-label">用户名:</label>-->
                <!--<div class="col-sm-10">-->
                    <!--<input type="email" class="form-control" id="id_username" placeholder="Email">-->
                <!--</div>-->
            <!--</div>-->
            <!--<div class="form-group">-->
                <!--<label for="id_password" class="col-sm-2 control-label">密码:</label>-->
                <!--<div class="col-sm-10">-->
                    <!--<input type="password" class="form-control" id="id_password" placeholder="Password">-->
                <!--</div>-->
            <!--</div>-->
            <!--<div class="form-group">-->
                <!--<div class="col-sm-offset-2 col-sm-2">-->
                    <!--<button type="submit" class="btn btn-default">登录</button>-->
                <!--</div>-->
            <!--</div>-->
        <!--</form>-->
        <!--{% endif %}-->
        <!---->
    </div>
</div>
{% endblock %}

bookseller/apps/register/templates/list.html
{% extends "base.html" %}

{% block title %}物品列表{% endblock %}

{% block content %}
<script src="../../../static/js/jquery-2.1.0.min.js"></script>
<script>
    $(document).ready(function(){
    $(".text_overflow").each(function()
    { var maxwidth=115;
        if($(this).text().length>maxwidth){
            $(this).text($(this).text().substring(0,maxwidth));
            $(this).html($(this).html()+'...');
    }
    });
});
</script>
<div class="container">
    <div class="row">
    <div class="col-md-10" id="taglist">
        {% include "tag_list.html" %}
    </div>
    </div>
    <div id="project">
        {% for item in item_list %}
        <div class="col-md-6 row well item_list half_page">
            <div class="col-md-4"><a href="{% url 'item_detail' item.id %}">
            {% if item.if_has_image %}
            <img src="{{ item.image.url }}" alt="..." class="img-rounded item_image">
            {% else %}
            <img src="/static/image/wutu.jpg" alt="..." class="img-rounded item_image">
            {% endif %}
            </a></div>
            <div class="col-md-5">
                <h4><a href="{% url 'item_detail' item.id %}">{{ item.title }}</a><small>{{personName}}</small></h4>
                <p class="text_overflow">
                {{ item.description }}
                </p>
            </div>
            <div class="col-md-3">
                <h3>{{ item.price }}元</h3>
            </div>
        </div>
        {% endfor %}
    </div>

</div>
<div class="container">
{% include "pagination.html" %}
</div>
{% endblock %}

bookseller/apps/register/templates/login.html
{% extends "base.html" %}

{% block title %}登录{% endblock %}

{% block content %}

<div class="container" id="register">
    <div class="col-md-1"></div>
    <div class="col-md-5">
        <h1>回到“卖东西”<br><small>释放你身边的闲置物品吧！</small></h1>
    </div>
    <div class="col-md-5">
        {% include "login_form.html" %}
    </div>
    <div class="col-md-1"></div>
</div>
{% endblock %}

bookseller/apps/register/templates/login_form.html
<form class="form-horizontal" role="form" action="" method="post" id="registerForm">
    {% csrf_token %}
    <div class="form-group">
        <label for="id_username" class="col-sm-3 control-label">用户名：</label>
        <div class="col-sm-9">
            <input type="text" class="form-control" id="id_username" placeholder="输入您的用户名" name="username">
            <span class="help-block" id="usernameHelp"></span>
        </div>
    </div>
    <div class="form-group">
        <label for="id_password" class="col-sm-3 control-label">密码：</label>
        <div class="col-sm-9">
            <input type="password" class="form-control" id="id_password" placeholder="输入您的密码" name="password">
        </div>
        <span class="help-block" id="passwordHelp"></span>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-3 col-sm-2">
            <button type="submit" class="btn btn-success">登录</button>
        </div>
    </div>
</form>

bookseller/apps/register/templates/register.html
{% extends "base.html" %}

{% block title %}注册{% endblock %}

{% block content%}
<script type="text/javascript" src="../../../static/js/jquery-2.1.0.min.js"></script>
<script language="javascript">
    $(document).ready(function() {
        $('#id_username').blur(function(){
            var username = $('#id_username').val();
            if (username){
                $.post("/ajax/checkuser/", {name:username},
                        function(result){
                            var ret = eval("(" + result + ")");
                            if (ret.result){
                                $('#div_uname_hint').html('<span>' + username + '已被注册</span>');
                            }else{
                                $('#div_uname_hint').html('<span>' + username + '可以注册</span>');
                            }});}});});

</script>
<body  onload="iniState()">
<div class="container" id="register">
    <div class="col-md-1">
    </div>
    <div class="col-md-4">
        <h1>加入<a href="/">卖东西</a><br><small>重新发现闲置的价值</small></h1>
    </div>
    <div class="col-md-5">
        <form name="frm_register" method="post"  onsubmit="">
            {% csrf_token %}
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon">用户名</span>
                    <input tabindex="1" placeholder="英文或数字下划线组合，长度6－20位，以字母开头" name="username" type="text" class="form-control" id="id_username"  size="20" maxlength="20"  onfocus="clearMsg('div_uname_hint')" onblur="verifyUName(username.value,'div_uname_hint')"/>
                </div>
                <div id="div_uname_hint" class="hint_error"></div>
            </div>
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon">电子邮箱</span>
                    <input tabindex="2" placeholder="方便你取得重要信息，包括找回密码" class="form-control" id="id_e_mail" name="e_mail" type="text" size="20" maxlength="32"  onfocus="clearMsg('div_emailhint')" onblur="verifyEmail(e_mail.value,'div_emailhint')"/>
                </div>
                <div id="div_emailhint" class="hint_error"></div>
            </div>
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon">密码</span>
                    <input tabindex="3" placeholder="英文或数字组合，区分大小写，长度6－20位" class="form-control" id="id_password" name="password" type="password"  size="20" maxlength="20" onfocus="clearMsg('div_pwd_hint')" onblur="verifyPwd(password.value,'div_pwd_hint')"/>
                </div>
                <div id="div_pwd_hint" class="hint_error"></div>
            </div>
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon">重输密码</span>
                    <input tabindex="4" class="form-control" id="repassword" name="repassword" type="password" size="20" maxlength="20" onfocus="clearMsg('div_chkpwd_hint')" onblur="verifychkPwd(repassword.value,password.value,'div_chkpwd_hint')"/>
                </div>
                <div id="div_chkpwd_hint" class="hint_error"></div>
            </div>
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon">电话号码</span>
                    <input tabindex="5" placeholder="11位阿拉伯数字组合" class="form-control" id="id_phoneNumber" name="phone_number" type="tel" size="20" maxlength="20" onfocus="clearMsg('div_tel_hint')" onblur="verifyTel(phone_number.value,'div_tel_hint')"/>
                </div>
                <div id="div_tel_hint" class="hint_error"></div>
            </div>
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon">QQ号码</span>
                    <input tabindex="6" placeholder="15位以下阿拉伯数字组合" class="form-control" id="id_QQNumber" name="qq_number" type="tel" size="20" maxlength="20" onfocus="clearMsg('div_qq_hint')" onblur="verifyQQ(qq_number.value,'div_qq_hint')"/>
                </div>
                <div id="div_qq_hint" class="hint_error"></div>
            </div>
            <div class="form-group">
                <div class="input-group">
                    <span class="input-group-addon">选择学校</span>
                    <select tabindex="7" name="address" id="selectSchool">
                        {% for school in school_list %}
                        <option value="{{ school }}" >{{ school }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="form-group">
                <div class="input-group">
                    <input tabindex="8" name="chk_accept" type="checkbox" value="checkbox" id="checkbox"/>
                    我已阅读并接受<a href="" target="_blank">服务条款</a>
                    <div id="div_accept_hint" class="hint_error"></div>
                    <button tabindex="9" type="submit" class="btn btn-success" onclick="verifyInput()">注册</button>
                    <button type="reset" class="btn-danger btn">重置</button>
                </div>
            </div>
        </form>
    </div>
    <div class="col-md-1">
    </div>
</div>
{% endblock %}